// <auto-generated />
namespace Projeto_Final_TCC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Fotos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fotos));
        
        string IMigrationMetadata.Id
        {
            get { return "202306020516220_Fotos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
